version: "3.9"

services:
  certnegativa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cert_negativa
    network_mode: host
    env_file: .env
    volumes:
      - ./app:/app                       # código
      - C:/CertData/salida:/data/salida  # negativas
      - //fs01/Digitalizacion_Jubilaciones:/data/expedientes  # UNC directa
      - C:/CertData/logs:/data/logs
      - C:/CertData/backups:/data/backups
    environment:
      PYTHONUNBUFFERED: 1
      DISPLAY: :99
    command: >
      bash -c "
        rm -f /tmp/.X99-lock && rm -rf /tmp/chrome_* &&
        Xvfb :99 -screen 0 1366x768x24 &
        exec python obtener_certificacion_negativa.py
      "
