version: "3.9"

services:
  certnegativa:
    build: .               # o image: certnegativa si ya la subiste
    container_name: cert_negativa
    restart: unless-stopped

    # --- ¡Aquí va! ---
    network_mode: host     # ⬅️  MISMA indentación que volumes, env_file, etc.

    env_file: .env
    volumes:
      - C:\CertData\informes:/data/informes
      - C:\CertData\logs:/data/logs
      - C:\CertData\backups:/data/backups
    # Cuando usas host-mode **no** se pueden mapear puertos (ports:),
    # porque el contenedor comparte la pila de red del host.
